export const overrideApis = () => {
  global.fetch = (api) => {
    let response = { data: {} };
    switch (api) {
      case "/api/fixtures/3":
        response.data = fixtureStates().set1;
        break;
      case "/api/whatever":
        response.data = [
          { Id: "1", Title: "Big Tournament" },
          { Id: "2", Title: "Little Tournament" },
          { Id: "3", Title: "Another Tournament" },
        ];
        break;
      default:
        response = { error: "No data for api " + api };
    }

    return Promise.resolve({
      ok: true,
      json: () => Promise.resolve(response)
    });
  };
};


function fixtureStates() {
  return {
    set1: [
      {
        id: 2871,
        tournamentId: 3,
        category: "Ladies Junior",
        groupNumber: 2,
        pitch: "Z1",
        stage: "group",
        scheduled: "2023-11-17T07:30:00.000Z",
        scheduledTime: "08:30",
        started: null,
        startedTime: null,
        team1: "Jersey Irish",
        goals1: 0,
        points1: 2,
        team2: "Copenhagen B",
        goals2: 5,
        points2: 12,
        umpireTeam: "Hamburg",
        played: 1,
      },
      {
        id: 2873,
        tournamentId: 3,
        category: "Ladies Junior",
        groupNumber: 2,
        pitch: "Z1",
        stage: "group",
        scheduled: "2023-11-17T08:00:00.000Z",
        scheduledTime: "09:00",
        started: null,
        startedTime: null,
        team1: "Nantes/Strasbourg Gaels B",
        goals1: 1,
        points1: 2,
        team2: "Copenhagen B",
        goals2: 3,
        points2: 2,
        umpireTeam: "Leuven",
        played: 1,
      },
      {
        id: 2875,
        tournamentId: 3,
        category: "Ladies Junior",
        groupNumber: 2,
        pitch: "Z1",
        stage: "group",
        scheduled: "2023-11-17T08:30:00.000Z",
        scheduledTime: "09:30",
        started: "2023-11-17T12:18:42.000Z",
        startedTime: "13:18",
        team1: "Jersey Irish",
        goals1: 1,
        points1: 4,
        team2: "Nantes/Strasbourg Gaels B",
        goals2: 1,
        points2: 4,
        umpireTeam: "Stockholm/A Coruña",
        played: 1,
      },
      {
        id: 2879,
        tournamentId: 3,
        category: "Ladies Junior",
        groupNumber: 1,
        pitch: "Z1",
        stage: "semis",
        scheduled: "2023-11-17T11:30:00.000Z",
        scheduledTime: "12:30",
        started: "2023-11-18T21:49:16.000Z",
        startedTime: "22:49",
        team1: "Stockholm/A Coruña",
        goals1: 1,
        points1: 8,
        team2: "Nantes/Strasbourg Gaels B",
        goals2: 3,
        points2: 5,
        umpireTeam: "~group:1/p:3",
        played: 1,
      },
      {
        id: 2880,
        tournamentId: 3,
        category: "Ladies Junior",
        groupNumber: 2,
        pitch: "Z1",
        stage: "runnersup",
        scheduled: "2023-11-17T12:10:00.000Z",
        scheduledTime: "13:10",
        started: "2023-11-22T21:57:58.000Z",
        startedTime: "22:57",
        team1: "Hamburg",
        goals1: 1,
        points1: 4,
        team2: "Jersey Irish",
        goals2: 3,
        points2: 1,
        umpireTeam: "~group:1/p:3",
        played: 1,
      },
      {
        id: 2881,
        tournamentId: 3,
        category: "Ladies Junior",
        groupNumber: 2,
        pitch: "Z1",
        stage: "semis",
        scheduled: "2023-11-17T12:40:00.000Z",
        scheduledTime: "13:40",
        started: "2023-11-30T15:56:27.000Z",
        startedTime: "16:56",
        team1: "Copenhagen B",
        goals1: null,
        points1: null,
        team2: "Leuven",
        goals2: null,
        points2: null,
        umpireTeam: "~semis:2/p:2",
        played: 0,
      },
      {
        id: 2882,
        tournamentId: 3,
        category: "Ladies Junior",
        groupNumber: 1,
        pitch: "Z1",
        stage: "runnersup",
        scheduled: "2023-11-17T14:00:00.000Z",
        scheduledTime: "15:00",
        started: null,
        startedTime: null,
        team1: "~semis:1/p:2",
        goals1: null,
        points1: null,
        team2: "~semis:2/p:2",
        goals2: null,
        points2: null,
        umpireTeam: "~group:1/p:1",
        played: 0,
      },
      {
        id: 2883,
        tournamentId: 3,
        category: "Ladies Junior",
        groupNumber: 1,
        pitch: "Z1",
        stage: "finals",
        scheduled: "2023-11-17T14:30:00.000Z",
        scheduledTime: "15:30",
        started: null,
        startedTime: null,
        team1: "Stockholm/A Coruña",
        goals1: null,
        points1: null,
        team2: "~semis:2/p:1",
        goals2: null,
        points2: null,
        umpireTeam: "~group:1/p:2",
        played: 0,
      },
    ],
    set2: [
      {
        "id": 2955,
        "tournamentId": 5,
        "category": "Mens",
        "groupNumber": 1,
        "pitch": "W1",
        "stage": "group",
        "scheduled": "2023-03-02T08:00:00.000Z",
        "scheduledTime": "09:00",
        "started": "2024-02-25T13:22:01.000Z",
        "startedTime": "14:22",
        "team1": "Den Haag A",
        "goals1": 1,
        "points1": 0,
        "team2": "Galicia",
        "goals2": 3,
        "points2": 1,
        "umpireTeam": "Kilconly",
        "played": 1
      },
      {
        "id": 2956,
        "tournamentId": 5,
        "category": "Mens",
        "groupNumber": 2,
        "pitch": "W1",
        "stage": "group",
        "scheduled": "2023-03-02T08:40:00.000Z",
        "scheduledTime": "09:40",
        "started": "2024-02-25T13:24:06.000Z",
        "startedTime": "14:24",
        "team1": "Den Haag B",
        "goals1": 1,
        "points1": 4,
        "team2": "Glinsk",
        "goals2": 3,
        "points2": 9,
        "umpireTeam": "St. Brendans",
        "played": 1
      },
      {
        "id": 2957,
        "tournamentId": 5,
        "category": "Mens",
        "groupNumber": 1,
        "pitch": "W1",
        "stage": "group",
        "scheduled": "2023-03-02T09:20:00.000Z",
        "scheduledTime": "10:20",
        "started": "2024-02-25T13:31:18.000Z",
        "startedTime": "14:31",
        "team1": "Galicia",
        "goals1": 1,
        "points1": 0,
        "team2": "Kilconly",
        "goals2": 3,
        "points2": 0,
        "umpireTeam": "Den Haag A",
        "played": 1
      },
      {
        "id": 2958,
        "tournamentId": 5,
        "category": "Mens",
        "groupNumber": 2,
        "pitch": "W1",
        "stage": "group",
        "scheduled": "2023-03-02T10:00:00.000Z",
        "scheduledTime": "11:00",
        "started": "2024-02-25T13:31:35.000Z",
        "startedTime": "14:31",
        "team1": "Glinsk",
        "goals1": 3,
        "points1": 4,
        "team2": "St. Brendans",
        "goals2": 1,
        "points2": 13,
        "umpireTeam": "Den Haag B",
        "played": 1
      },
      {
        "id": 2959,
        "tournamentId": 5,
        "category": "Mens",
        "groupNumber": 1,
        "pitch": "W1",
        "stage": "group",
        "scheduled": "2023-03-02T10:40:00.000Z",
        "scheduledTime": "11:40",
        "started": "2024-02-25T13:32:20.000Z",
        "startedTime": "14:32",
        "team1": "Kilconly",
        "goals1": 1,
        "points1": 4,
        "team2": "Den Haag A",
        "goals2": 2,
        "points2": 0,
        "umpireTeam": "Galicia",
        "played": 1
      },
      {
        "id": 2960,
        "tournamentId": 5,
        "category": "Mens",
        "groupNumber": 2,
        "pitch": "W1",
        "stage": "group",
        "scheduled": "2023-03-02T11:20:00.000Z",
        "scheduledTime": "12:20",
        "started": "2024-02-25T13:32:52.000Z",
        "startedTime": "14:32",
        "team1": "St. Brendans",
        "goals1": 1,
        "points1": 4,
        "team2": "Den Haag B",
        "goals2": 3,
        "points2": 0,
        "umpireTeam": "Glinsk",
        "played": 1
      },
      {
        "id": 2961,
        "tournamentId": 5,
        "category": "Mens",
        "groupNumber": 5,
        "pitch": "W1",
        "stage": "runnersup",
        "scheduled": "2023-03-02T12:40:00.000Z",
        "scheduledTime": "13:40",
        "started": null,
        "startedTime": null,
        "team1": "~A/3",
        "goals1": null,
        "points1": null,
        "team2": "~B/3",
        "goals2": null,
        "points2": null,
        "umpireTeam": "~A/2",
        "played": 0
      },
      {
        "id": 2962,
        "tournamentId": 5,
        "category": "Mens",
        "groupNumber": 1,
        "pitch": "W1",
        "stage": "semis",
        "scheduled": "2023-03-02T13:20:00.000Z",
        "scheduledTime": "14:20",
        "started": null,
        "startedTime": null,
        "team1": "~A/1",
        "goals1": null,
        "points1": null,
        "team2": "~B/2",
        "goals2": null,
        "points2": null,
        "umpireTeam": "~P56/1",
        "played": 0
      },
      {
        "id": 2963,
        "tournamentId": 5,
        "category": "Mens",
        "groupNumber": 2,
        "pitch": "W1",
        "stage": "semis",
        "scheduled": "2023-03-02T14:00:00.000Z",
        "scheduledTime": "15:00",
        "started": null,
        "startedTime": null,
        "team1": "~A/2",
        "goals1": null,
        "points1": null,
        "team2": "~B/1",
        "goals2": null,
        "points2": null,
        "umpireTeam": "~A/2",
        "played": 0
      },
      {
        "id": 2964,
        "tournamentId": 5,
        "category": "Mens",
        "groupNumber": 1,
        "pitch": "W1",
        "stage": "finals",
        "scheduled": "2023-03-02T15:00:00.000Z",
        "scheduledTime": "16:00",
        "started": null,
        "startedTime": null,
        "team1": "~S1/1",
        "goals1": null,
        "points1": null,
        "team2": "~S2/1",
        "goals2": null,
        "points2": null,
        "umpireTeam": "~P56/2",
        "played": 0
      }
    ]
  }
}